from __future__ import annotations

from pathlib import Path

import pandas as pd
import yaml


def write_report(
    out_dir: Path,
    hypothesis: dict,
    lint,
    results: dict[str, dict],
    gates_test,
    trades: dict[str, pd.DataFrame],
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Research report: {hypothesis.get('id', hypothesis.get('name', 'unnamed'))}",
        "",
        "## Hypothesis",
        f"- **Claim**: {hypothesis.get('claim', '')}",
        f"- **Decision time**: {hypothesis.get('decision_time', '')}",
        f"- **Fill model**: {hypothesis.get('fill_model', '')}",
        f"- **Exit**: {hypothesis.get('exit', '')}",
        "",
        "## Lookahead lint",
        f"- OK: **{lint.ok}**",
    ]
    for e in lint.errors:
        lines.append(f"- ERROR: {e}")
    for w in lint.warnings:
        lines.append(f"- WARN: {w}")

    lines += ["", "## Splits performance", ""]
    lines.append("| split | n_trades | fill_rate | win_rate | expectancy | PF | total_ret | max_dd |")
    lines.append("|-------|----------|-----------|----------|------------|----|-----------|--------|")
    for split, perf in results.items():
        lines.append(
            "| {split} | {n_trades} | {fill_rate} | {win_rate} | {expectancy} | {profit_factor} | {total_return} | {max_drawdown} |".format(
                split=split,
                n_trades=perf.get("n_trades"),
                fill_rate=_fmt(perf.get("fill_rate")),
                win_rate=_fmt(perf.get("win_rate")),
                expectancy=_fmt(perf.get("expectancy")),
                profit_factor=_fmt(perf.get("profit_factor")),
                total_return=_fmt(perf.get("total_return")),
                max_drawdown=_fmt(perf.get("max_drawdown")),
            )
        )

    lines += ["", "## Gates", f"- PASS: **{gates_test.ok}**"]
    for e in gates_test.errors:
        lines.append(f"- FAIL: {e}")
    for w in gates_test.warnings:
        lines.append(f"- WARN: {w}")

    lines += [
        "",
        "## Verdict",
        (
            "**REJECT** — failed lint or gates."
            if (not lint.ok or not gates_test.ok)
            else "**CANDIDATE** — passed lint + val/test gates; still needs paper trading."
        ),
        "",
        "_Generated by ashare-research-lab. Not investment advice._",
    ]

    md = out_dir / "report.md"
    md.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # artifacts
    (out_dir / "hypothesis.yaml").write_text(
        yaml.safe_dump(hypothesis, allow_unicode=True, sort_keys=False), encoding="utf-8"
    )
    summary = pd.DataFrame(results).T
    summary.to_csv(out_dir / "metrics.csv")
    summary.to_json(out_dir / "metrics.json", orient="index", indent=2)
    for name, tdf in trades.items():
        if tdf is not None and not tdf.empty:
            tdf.to_csv(out_dir / f"trades_{name}.csv", index=False)
    return md


def _fmt(x) -> str:
    if x is None:
        return ""
    try:
        if x != x:  # NaN
            return ""
        return f"{float(x):.4f}"
    except Exception:
        return str(x)
