from __future__ import annotations

from pathlib import Path

import pandas as pd
import yaml


def write_report(
    out_dir: Path,
    hypothesis: dict,
    lint,
    results: dict[str, dict],
    gates_test,
    trades: dict[str, pd.DataFrame],
    *,
    assumption_audit=None,
    stress: dict | None = None,
    final_verdict: str = "REJECT",
) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Research report: {hypothesis.get('id', hypothesis.get('name', 'unnamed'))}",
        "",
        "## Hypothesis",
        f"- **Claim**: {hypothesis.get('claim', '')}",
        f"- **Decision time**: {hypothesis.get('decision_time', '')}",
        f"- **Fill model**: {hypothesis.get('fill_model', '')}",
        f"- **Exit**: {hypothesis.get('exit', '')}",
        "",
        "## Lookahead lint",
        f"- OK: **{lint.ok}**",
    ]
    for e in lint.errors:
        lines.append(f"- ERROR: {e}")
    for w in lint.warnings:
        lines.append(f"- WARN: {w}")

    lines += ["", "## Assumption audit", ""]
    if assumption_audit is None:
        lines.append("- (not run)")
    else:
        lines.append(f"- grade: **{assumption_audit.grade}**")
        lines.append(f"- ok_for_candidate: {assumption_audit.ok_for_candidate}")
        lines.append(f"- ok_for_weak: {assumption_audit.ok_for_weak}")
        for e in assumption_audit.errors:
            lines.append(f"- FAIL: {e}")
        for w in assumption_audit.warnings:
            lines.append(f"- WARN: {w}")
        ass = hypothesis.get("assumptions") or {}
        if ass:
            lines.append(f"- declared: signal_fidelity={ass.get('signal_fidelity')}, "
                         f"fill_realism={ass.get('fill_realism')}, proxies={ass.get('proxies')}")

    lines += ["", "## Splits performance", ""]
    lines.append("| split | n_trades | fill_rate | win_rate | expectancy | PF | total_ret | max_dd |")
    lines.append("|-------|----------|-----------|----------|------------|----|-----------|--------|")
    for split, perf in results.items():
        lines.append(
            "| {split} | {n_trades} | {fill_rate} | {win_rate} | {expectancy} | {profit_factor} | {total_return} | {max_drawdown} |".format(
                split=split,
                n_trades=perf.get("n_trades"),
                fill_rate=_fmt(perf.get("fill_rate")),
                win_rate=_fmt(perf.get("win_rate")),
                expectancy=_fmt(perf.get("expectancy")),
                profit_factor=_fmt(perf.get("profit_factor")),
                total_return=_fmt(perf.get("total_return")),
                max_drawdown=_fmt(perf.get("max_drawdown")),
            )
        )

    if stress:
        lines += ["", "## Fill stress (executable alternative)", ""]
        lines.append(f"- model: `{stress.get('fill_model')}`")
        lines.append(f"- ok: **{stress.get('ok')}**")
        for split, perf in (stress.get("results") or {}).items():
            lines.append(
                f"- {split}: n={perf.get('n_trades')} exp={_fmt(perf.get('expectancy'))} "
                f"dd={_fmt(perf.get('max_drawdown'))}"
            )
        for e in stress.get("errors") or []:
            lines.append(f"- FAIL: {e}")

    lines += ["", "## Metric gates", f"- PASS: **{gates_test.ok}**"]
    for e in gates_test.errors:
        lines.append(f"- FAIL: {e}")
    for w in gates_test.warnings:
        lines.append(f"- WARN: {w}")

    meaning = {
        "REJECT": "未过 lint / 假设审计 / 指标门禁 / 成交压力测试。",
        "WEAK_CANDIDATE": "指标勉强过，但信号或成交假设偏弱——只配研究，不配加仓。",
        "CANDIDATE": "假设相对诚实且 val/test 过门禁；仍需模拟盘验证成交。",
    }
    lines += [
        "",
        "## Verdict",
        f"**{final_verdict}** — {meaning.get(final_verdict, '')}",
        "",
        "_Generated by ashare-research-lab. Not investment advice._",
    ]

    md = out_dir / "report.md"
    md.write_text("\n".join(lines) + "\n", encoding="utf-8")

    (out_dir / "hypothesis.yaml").write_text(
        yaml.safe_dump(hypothesis, allow_unicode=True, sort_keys=False), encoding="utf-8"
    )
    summary = pd.DataFrame(results).T
    summary.to_csv(out_dir / "metrics.csv")
    payload = {
        "metrics": results,
        "verdict": final_verdict,
        "assumption_grade": getattr(assumption_audit, "grade", None),
        "stress": {
            k: v
            for k, v in (stress or {}).items()
            if k != "results"
        },
    }
    if stress and stress.get("results"):
        payload["stress_metrics"] = stress["results"]
    import json

    (out_dir / "metrics.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8"
    )
    # keep flat metrics.csv; also write legacy-friendly split table
    for name, tdf in trades.items():
        if tdf is not None and not tdf.empty:
            tdf.to_csv(out_dir / f"trades_{name}.csv", index=False)
    (out_dir / "verdict.txt").write_text(final_verdict + "\n", encoding="utf-8")
    return md


def _fmt(x) -> str:
    if x is None:
        return ""
    try:
        if x != x:  # NaN
            return ""
        return f"{float(x):.4f}"
    except Exception:
        return str(x)
